name: Terraform Module Releaser
on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Closed required
    branches:
      - main

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki
  pull-requests: write # Required to comment on pull request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1
        with:
          terraform-docs-version: v0.20.0
          use-ssh-source-format: true
          wiki-usage-template: |
            ## Usage in Terragrunt

            To use this module in your Terragrunt deploy, refer to the below example:
            ```hcl
            terraform {
              source = "git@github.com:hirevue-org/hv-terraform-modules.git?ref={{latest_tag}}"
            }
            ```

            ## Usage in Terraform

            ```hcl
            module "{{module_name_terraform}}" {
              source = "git@github.com:hirevue-org/hv-terraform-modules.git?ref={{latest_tag}}"

              # See inputs below for additional required parameters
            }
            ```
